# Generated by Django 3.2.7 on 2021-09-14 13:42
from django.conf import settings
from django.db import migrations, models

def car_labels(apps, schema_editor):
    Regions = apps.car_labels("cars", "cars_labels")
    with open("{}/car_labels.json".format(settings.DATA_ROOT), "r") as region_file:
        region_data = json.load(region_file)
        for region in region_data:
            new_region = Regions(name=region['name'], is_federal_city=region['is_federal_city'])
            new_region.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='CarsLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Model')),
                ('country', models.CharField(max_length=64, verbose_name='Country')),
            ],
        ),
    ]
